version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build phase"
      - echo "Current directory is: $(pwd)"
      - echo "Moving to http-api-gateway"
      - cd http-api-gateway
      - echo "Loggin in into Amazon ECR"
  build:
    commands:
      - echo "Entering the build phase"
  post_build:
    commands:
      - echo "Entering the post build phase"
artifacts:
  files:
    - imagedefinitions.json