version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build phase"
      - echo "Entering the api gateway"
      - cd http-api-gateway
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com 
  build:
    commands:
      - echo "Entering the build phase"
  post_build:
    commands:
      - echo "Entering the post build phase"
artifacts:
  files:
    - imagedefinitions.json