version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== STARTING BUILD ==="
      - echo "Current directory: $(pwd)"
      - echo "Listing root directory:"
      - ls -la
      - echo "Changing to api-gateway directory..."
      - cd http-api-gateway
      - echo "Now in: $(pwd)"
      - echo "Listing api-gateway contents:"
      - ls -la
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Build would happen here"
      - echo "Simulating successful build"
  post_build:
    commands:
      - echo "=== POST BUILD ==="
      - echo "Build completed successfully"
      - echo "Creating dummy imagedefinitions.json..."
      - echo '[{"name":"app-container","imageUri":"123456.dkr.ecr.region.amazonaws.com/repo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json