version: 0.2

phases:
  pre_build:
    commands:
      - echo "Testing ECR buildspec file"
  build:
    commands:
      - echo "Entering the build phase"
  post_build:
    commands:
      - echo "Entering the post build phase"
artifacts:
  files:
    - imagedefinitions.json