version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build phase"
      - echo "Entering the api gateway"
      - cd http-api-gateway
  build:
    commands:
      - echo "Entering the build phase"
  post_build:
    commands:
      - echo "Entering the post build phase"
artifacts:
  files:
    - imagedefinitions.json