import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer'
import * as path from 'path';


@Injectable()
export class EmailsService {
    private transporter: nodemailer.Transporter

    constructor(private configService: ConfigService) {
        //configuring the nodemailer transporter
        this.transporter = nodemailer.createTransport({
            host: 'smtp.gmail.com',
            port: 587,
            secure: false,
            auth: {
                user: this.configService.get<string>('SMTP_USER'),
                pass: this.configService.get<string>('SMTP_PASS'),
            },
            logger: true,
            debug: true,
            tls: {
                rejectUnauthorized: false
            }
        });

    }

    async sendNewPasswordEmail(to: string, password: string, verifyEmail: string) {
        try {
            const info = await this.transporter.sendMail({
                from: this.configService.get<string>("SMTP_USER"),
                to,
                subject: "Welcome to Our Law Firm",
                text: `Welcome to our law firm!\nYour autogenerated password is: ${password}\nPlease verify your email here: ${verifyEmail}`,
                attachments: [
                    {
                        filename: "justice.png",
                        path: path.resolve("./src/utils/logos/justice.png"),
                        cid: "companyLogo",
                    },
                ],
                html: `
              <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
                
                <!-- Logo -->
                <div style="text-align: center; margin-bottom: 20px;">
                  <img src="cid:companyLogo" alt="Company Logo" width="120" style="display:block;margin:auto;" />
                </div>
                
                <!-- Heading -->
                <h2 style="color: #333; text-align: center;">Welcome Aboard!</h2>
                
                <!-- Message -->
                <p style="color: #555; font-size: 14px; line-height: 1.6;">
                  Hi there,<br/><br/>
                  Welcome to our law firm, we are happy to have you on board!<br/>
                  This is your temporary generated password you can use to log in.<br/>
                  Once you have logged in, make sure to change your password.
                </p>
                
                <!-- Password Block -->
                <div style="text-align: center; margin: 30px 0;">
                  <p style="background: #f5f5f5; color: #333; padding: 12px 24px; border-radius: 5px; font-size: 16px; display: inline-block;">
                    Password: <b>${password}</b>
                  </p>
                </div>
      
                <!-- Verification Button -->
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${verifyEmail}" target="_blank" 
                    style="background: #28a745; color: #fff; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; font-size: 16px; display: inline-block;">
                    Verify Your Email
                  </a>
                </div>
                
                <!-- Footer -->
                <p style="color: #999; font-size: 12px; text-align: center;">
                  © ${new Date().getFullYear()} LawFirm. All rights reserved.<br/>
                  This is an automated message, please do not reply.
                </p>
              </div>
            `,
            });
            console.log("email successfully sent to:", info.messageId);
            return { status: "success" };
        } catch (error) {
            return { status: "err", message: error.message };
        }
    }

    async sendPasswordResetUrl(to: string, resetUrl: string) {
        try {
            console.log("Sending reset email to:", to, resetUrl);
            const info = await this.transporter.sendMail({
                from: this.configService.get<string>("SMTP_USER"),
                to,
                subject: "Forgot Password",
                text: "This is your password reset url, click on the link below to reset your password",
                attachments: [{
                    filename: 'justice.png',
                    path: path.resolve('./src/utils/logos/justice.png'),
                    cid: "companyLogo"
                }],
                html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
        
                    <div style="text-align: center; margin-bottom: 20px;">
                    <img src="cid:companyLogo" alt="Company Logo" width="120" style="display:block;margin:auto;" />
                    </div>
                    
                    <!-- Heading -->
                    <h2 style="color: #333; text-align: center;">Password Reset Request</h2>
                    
                    <!-- Message -->
                    <p style="color: #555; font-size: 14px; line-height: 1.6;">
                    Hi there,<br/><br/>
                    We received a request to reset your password. Click the button below to reset it. 
                    If you didn’t request this, you can safely ignore this email.
                    </p>
                    
                    <!-- Button -->
                    <div style="text-align: center; margin: 30px 0;">
                    <a href="${resetUrl}" style="background: #007bff; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-size: 16px;">
                        Reset Password
                    </a>
                    </div>
                    
                    <!-- Footer -->
                    <p style="color: #999; font-size: 12px; text-align: center;">
                    © ${new Date().getFullYear()} LawFirm. All rights reserved.<br/>
                    This is an automated message, please do not reply.
                    </p>
                </div>
                `
            })

            return { status: 'success', info: info.messageId }
        } catch (error) {
            return { status: 'error', msg: error.msg }
        }
    }

    async sendVerifiedEmailNotification(to: string) {
        try {
            console.log("Sending reset email to:", to);
            const info = await this.transporter.sendMail({
                from: this.configService.get<string>("SMTP_USER"),
                to,
                subject: "Verified Email",
                text: "Email Verified",
                attachments: [{
                    filename: 'justice.png',
                    path: path.resolve('./src/utils/logos/justice.png'),
                    cid: "companyLogo"
                }],
                html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
        
                    <div style="text-align: center; margin-bottom: 20px;">
                    <img src="cid:companyLogo" alt="Company Logo" width="120" style="display:block;margin:auto;" />
                    </div>
                    
                    <!-- Heading -->
                    <h2 style="color: #333; text-align: center;">User Verified!</h2>
                    
                    <!-- Message -->
                    <p style="color: #555; font-size: 14px; line-height: 1.6;">
                    Hi there,<br/><br/>
                    Your email has been successfully verified, you can now log in to the system using your username and password. Thank you.
                    </p>
                    
                    <!-- Footer -->
                    <p style="color: #999; font-size: 12px; text-align: center;">
                    © ${new Date().getFullYear()} LawFirm. All rights reserved.<br/>
                    This is an automated message, please do not reply.
                    </p>
                </div>
                `
            })

            return { status: 'success', info: info.messageId }
        } catch (error) {
            return { status: 'error', msg: error.msg }
        }
    }

    async resendVerificationUrl(to: string, verifyUrl: string) {
        try {
            console.log("Sending reset email to:", to, verifyUrl);
            const info = await this.transporter.sendMail({
                from: this.configService.get<string>("SMTP_USER"),
                to,
                subject: "Verification Email",
                text: "This is your verification email, click on the link below to verify your email",
                attachments: [{
                    filename: 'justice.png',
                    path: path.resolve('./src/utils/logos/justice.png'),
                    cid: "companyLogo"
                }],
                html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
        
                    <div style="text-align: center; margin-bottom: 20px;">
                    <img src="cid:companyLogo" alt="Company Logo" width="120" style="display:block;margin:auto;" />
                    </div>
                    
                    <!-- Heading -->
                    <h2 style="color: #333; text-align: center;">Verification Email</h2>
                    
                    <!-- Message -->
                    <p style="color: #555; font-size: 14px; line-height: 1.6;">
                    Hi there,<br/><br/>
                    We received a request to verify your account. Click the button below to verify it. 
                    If you didn’t request this, you can safely ignore this email.
                    </p>
                    
                    <!-- Verification Button -->
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${verifyUrl}" target="_blank" 
                    style="background: #28a745; color: #fff; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; font-size: 16px; display: inline-block;">
                    Verify Your Email
                  </a>
                </div>
                    
                    <!-- Footer -->
                    <p style="color: #999; font-size: 12px; text-align: center;">
                    © ${new Date().getFullYear()} LawFirm. All rights reserved.<br/>
                    This is an automated message, please do not reply.
                    </p>
                </div>
                `
            })

            return { status: 'success', info: info.messageId }
        } catch (error) {
            return { status: 'error', msg: error.msg }
        }
    }
}
